// ============================================================
// FILE: src/user/user.service.spec.ts
// ROLE: Unit Test (scaffold) — a basic test file generated by the
//       NestJS CLI that only verifies UserService can be instantiated.
//       Like the controller test, this is a SCAFFOLD that needs mocking
//       to actually work.
// DEPENDS ON: UserService, @nestjs/testing
// CALLED BY: Jest test runner (via `npm run test`)
// ============================================================

// Test and TestingModule are the core utilities for creating isolated
// NestJS testing modules without booting the full application.
import { Test, TestingModule } from '@nestjs/testing';

// Import the service we're testing.
import { UserService } from './user.service';

// describe() creates a test suite for UserService.
describe('UserService', () => {
  // Variable to hold the service instance being tested.
  let service: UserService;

  // beforeEach() sets up a fresh test environment before each test case.
  beforeEach(async () => {
    // Create a mini NestJS module with only UserService as a provider.
    //
    // ⚠️ NOTE: This test is INCOMPLETE and would FAIL if run, because
    // UserService depends on Repository<User> (injected via @InjectRepository(User)),
    // but no repository is provided here. NestJS would throw:
    // "Nest can't resolve dependencies of the UserService (?)"
    //
    // To fix this, you would need to provide a MOCK repository:
    //   providers: [
    //     UserService,
    //     {
    //       provide: getRepositoryToken(User),  // from @nestjs/typeorm
    //       useValue: {                         // mock object with the methods you use
    //         find: jest.fn().mockResolvedValue([]),
    //         findOneBy: jest.fn().mockResolvedValue(null),
    //         create: jest.fn().mockReturnValue({}),
    //         save: jest.fn().mockResolvedValue({}),
    //         update: jest.fn().mockResolvedValue({}),
    //         delete: jest.fn().mockResolvedValue({ affected: 1 }),
    //       },
    //     },
    //   ]
    //
    // This would allow UserService to be instantiated without a real database.
    const module: TestingModule = await Test.createTestingModule({
      providers: [UserService],
    }).compile();

    // Retrieve the UserService instance from the test module's DI container.
    service = module.get<UserService>(UserService);
  });

  // A minimal smoke test — checks that the service was successfully created.
  // As noted above, this would fail without providing the mock repository.
  it('should be defined', () => {
    expect(service).toBeDefined();
  });
});
