// ============================================================
// FILE: src/app.controller.ts
// ROLE: Controller — handles incoming HTTP requests to the root
//       path ("/") and delegates the work to AppService.
//       This is the default controller generated by the NestJS CLI.
// DEPENDS ON: AppService (injected via constructor)
// CALLED BY: NestJS routing engine when a GET / request arrives
// ============================================================

// Controller is a decorator that marks a class as a NestJS controller.
// A controller's job is to receive HTTP requests and return responses.
// Get is a decorator that maps a method to the HTTP GET verb.
import { Controller, Get } from '@nestjs/common';

// AppService contains the business logic for this controller.
// We import it here so TypeScript knows the type, and NestJS can inject it.
import { AppService } from './app.service.js';

// @Controller() marks this class as a NestJS controller.
// The empty parentheses @Controller() mean this controller handles the ROOT path "/".
// If we wrote @Controller('hello'), all routes in this class would be under "/hello".
// NestJS reads this decorator at startup to know which routes this class handles.
@Controller()
export class AppController {
  // The constructor receives an instance of AppService via dependency injection.
  //
  // 'private readonly appService: AppService' is a TypeScript shorthand that does
  // THREE things at once:
  // 1. Declares a class property called 'appService'
  // 2. Makes it 'private' (only accessible within this class)
  // 3. Makes it 'readonly' (cannot be reassigned after construction)
  //
  // You NEVER write 'new AppService()' yourself — NestJS's dependency injection
  // container creates the AppService instance and passes it here automatically.
  // This works because AppService is listed in AppModule's 'providers' array.
  constructor(private readonly appService: AppService) {}

  // @Get() maps this method to HTTP GET requests on the root path "/".
  // Combined with @Controller() (no prefix), the full route is: GET /
  //
  // When someone sends GET http://localhost:3000/, NestJS calls this method.
  // The return value is automatically sent as the HTTP response body.
  // Since it returns a string, NestJS sends it as plain text with status 200 OK.
  @Get()
  getHello(): string {
    // Delegate to the service layer — the controller does NOT contain logic.
    // It just calls the service and returns whatever the service returns.
    // This separation keeps the controller thin and the logic reusable.
    return this.appService.getHello();
  }
}
